### ISSUE TITLE
Create a chat webapp with elegant UI on webllm.mlc.ai

### ISSUE THREAD

**Issue by Neet-Nestor** [mlc-ai/web-llm#391]
Currently UI of web-llm demo on https://webllm.mlc.ai/ is pretty preliminary. It's ok as a bare demo, but to better market this project we should make a more webapp with a more elegant UI.

We could integrate web-llm into a open-source chatbot UI like one from the following list:
https://github.com/billmei/every-chatgpt-gui

Currently, the UI of the Web-LLM demo hosted at [webllm.mlc.ai](https://webllm.mlc.ai/) serves its purpose as a basic demonstration. However, to enhance the marketability of the project, it's imperative to elevate the user experience by implementing a more elegant and user-friendly interface.

One effective approach to achieve this is by integrating Web-LLM into an open-source chatbot UI framework. A list of available candidates is [Every ChatGPT GUI](https://github.com/billmei/every-chatgpt-gui).

Integrating Web-LLM with a sophisticated chatbot UI not only improves its aesthetics but also enhances its usability and appeal to potential users and stakeholders. This integration will offer a seamless and intuitive interaction experience, contributing significantly to the project's marketability and adoption.

I'm interested in creating one and I'll post my update there in this issue thread.

**Comment by Neet-Nestor** [comment]
**Update**

I've developed a web application integrating Web-LLM with [NextChat (ChatGPT Next Web)](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web).

You can access the live demo at https://chat.neet.coffee/ and here's a screenshot:

![screenshot of web-llm Chat UI](https://github.com/mlc-ai/web-llm/assets/23090573/ad215895-707b-47ae-b184-6d5044e36244)

Please note that this integration is currently in its preliminary demonstration phase. Further modifications and enhancements are necessary to ensure all functionalities work seamlessly.

**Comment by Neet-Nestor** [comment]
The chat webapp https://chat.neet.coffee/ has been updated to:

- Resolve the repeated model initialization issue
- Support service-worker
- Support streaming
- Support more customization

As the next step, I will work on optimizing the model management and loading since currently the model loading still takes 20+ seconds with cache and it is required on every page load.

**Comment by Neet-Nestor** [comment]
**Improvements:**

- [ ] Display Model Information: The name of the AI model being used should always be displayed in the user interface, as changing the model variant is a key feature.
- [ ] Show Performance Stats: Provide a section in the UI to display performance statistics related to the response generation process.
- [ ] Revise User and Bot Avatars: Replace the user and bot avatars with more meaningful representations, such as the MLC logo plus model name for the bot, and default to the user's text for the user.
- [ ] Provide Guidance for Shortcuts: Add a section on the left side of the UI to show guidance on important shortcut settings.
- [ ] Rearrange Settings:
  - [ ] Move the setting for changing sampling parameters (e.g., temperature) to a more prominent location.
  - [ ] If the model name is displayed separately, the model selection setting may be less important.

- [ ] Clarify Terminology:  Renaming "mask" to "system prompt template."

- [ ] Streamline Long Chat Experience:
  - [ ] Optimize the multi-round chat experience to avoid excessive processing time and unintended behavior due to context memorization.
  - [ ] Consider removing the contextual prompt feature initially and focus on providing a streamlined, slick UI for multi-round chat.

**Prioritize Key Features:**
- [ ] Ensure the following features are available and easily accessible
- [ ] Changing settings (e.g., temperature) and system prompts
- [ ] Selecting AI models (with eager loading to reduce bootstrap time)
- [ ] Providing a simple set of validated prompt libraries
- [ ] Ability to stop generation and reset the AI model (in case of bugs)
- [ ] Ability to share the current session settings (system prompt, model, and other settings) via a shareable URL

**Comment by Neet-Nestor** [comment]
Close issue and move tracking to https://github.com/mlc-ai/web-llm-chat

**Comment by flatsiedatsie** [comment]
Secret Llama recently created what you describe already: 

https://secretllama.com/

https://github.com/abi/secret-llama

Perhaps it would be an idea to work with that project?

I will also be releasing a 100% browser-based project soon that heavily builds on WebLLM. It will showcases it's many abilities. 

It will also go beyond the, in my opinion, tired "yet another OpenAI clone" formula. Some screenshots:

<img width="1650" alt="Screenshot 2024-05-17 at 11 26 53" src="https://github.com/mlc-ai/web-llm/assets/805405/b17a054d-ce04-4577-8b6f-8775c565e6cd">
<img width="1527" alt="Screenshot 2024-05-17 at 11 33 16" src="https://github.com/mlc-ai/web-llm/assets/805405/e7becab5-7c1c-4a6f-b4f9-c91bd15b6164">
<img width="1302" alt="Screenshot 2024-05-17 at 11 39 12" src="https://github.com/mlc-ai/web-llm/assets/805405/67dd1883-7521-4c18-9ecc-b5f848d62363">

**Comment by Neet-Nestor** [comment]
> Perhaps of interest: Secret Llama recently created what you describe as well:
> 
> https://secretllama.com/
> 
> https://github.com/abi/secret-llama
> 
> https://www.reddit.com/r/LocalLLaMA/comments/1cjjxc6/i_built_a_free_inbrowser_llm_chatbot_powered_by/
> 

This is interesting and thank you for sharing! The discussion there validates my assumption that a user-friendly, production-ready, streamlined UI for web-llm is expected by many users.

I had a brief look of their codebase, and realized that the author created the project from scratch and the current stage of the webapp UI is still relatively premature. I did it in a different approach by integrating web-llm to a more mature open-source chat UI projects in hope to avoid reinvent the wheels and be able to quickly launch an elegant and user-friendly webapp product to the public.

Therefore, I will continue working on this as a separate project, [web-llm-chat](https://github.com/mlc-ai/web-llm-chat/issues/6), under mlc.ai, but I will try reach out to secret llama's authors for potential collaborations.

> FYI, I will also be releasing a 100% browser-based project soon that heavily builds on WebLLM. It will showcases it's many abilities.

Your project looks very cool with a comprehensive set of features. Best luck on it!
