### ISSUE TITLE
[Tracking][WebLLM] Runtime updates

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/web-llm#429]
### Overview

There are various runtime things we'd like to update and complete in WebLLM

- [x] Support grammar for Llama 3, hence update Hermes 2 support from Mistral to Llama3-based
  - Compile following changes to MLC runtime wasm
    - https://github.com/mlc-ai/mlc-llm/pull/2248
    - https://github.com/mlc-ai/mlc-llm/pull/2335
    - https://github.com/mlc-ai/mlc-llm/pull/2416
  - Reflected in 0.2.39; completed via: https://github.com/mlc-ai/web-llm/pull/433
- [x] Support Phi-3 mini
  - Reflected in 0.2.39; completed via: https://github.com/mlc-ai/web-llm/pull/433
- [x] ModelRecord enhancements:
  - [x] Remove `resolve/main` from URL of `model`, and update `model_id` to be repo name
  - [x] Rename `model_url` and `model_lib_url` to `model` and `model_lib`
  - Completed via https://github.com/mlc-ai/web-llm/pull/435
- [x] Update function calling API to better accommodate Hermes 2
  - Added via https://github.com/mlc-ai/web-llm/pull/451
- [x] Remove `mean_gen_len`, `max_gen_len`, `shift_fill_factor` usages
  - Follow logic in https://github.com/mlc-ai/mlc-llm/blob/4538cc724c1e66917c34b59f3747f8d828a6c7c5/python/mlc_llm/interface/chat.py#L174
  - Completed via https://github.com/mlc-ai/web-llm/pull/457
- [x] Add OpenAI new field `include_usage`
  - Completed via https://github.com/mlc-ai/web-llm/pull/456
- [x] Allow users to configure KVCache: the KVCache size, and whether to use sliding window
  - Completed via https://github.com/mlc-ai/web-llm/pull/455
- [ ] Add Streamer for better emoji support (for both Llama3-like tokenizers and Llama2-like tokenizers)

**Comment by CharlieFRuan** [comment]
Will add Streamer support in the future if needed. It seems recent models do not have emoji issues.
