### ISSUE TITLE
[Tracking][WebLLM] Revamp documentations

### ISSUE THREAD

**Issue by CharlieFRuan** [mlc-ai/web-llm#430]
We'd like to complete the following items for WebLLM documentation

- [x] Update github README: https://github.com/mlc-ai/web-llm
  - Also make sure npm package is sync'd https://www.npmjs.com/package/@mlc-ai/web-llm
- [x] Update / re-organize website: https://webllm.mlc.ai/
  - [ ] e.g. Add code snippet to show case simple usage
- [x] Re-organize documentation: https://llm.mlc.ai/docs/deploy/javascript.html
  - WebLLM Quickstart (brief intro to the project, quick start example)
  - OpenAI-like Capabilities
      - Chat completion
      - Streaming
      - JSON mode & JSON schema
      - Function calling
      - Logit processing
      - Seeding
  - Supported Models
      - Prebuilt Models
      - Verify Installation for compiling models
      - Bring Your own model variant
      - Bring your own model library
  - Building agents / WebApp with WebLLM
      - Service Worker
      - Web Worker
      - Chrome extension
  - FAQ & API (a link to typedoc)
